spring:
    application:
        name: backapp
    datasource:
      url: jdbc:h2:./test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password:
    h2:
      console:
        enabled: true

flyway:
  enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

